version: '3.8'

services:
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coinflip
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    restart: always
    networks:
      - app-network

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne coinflip.asgi:application --bind 0.0.0.0 --port 8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/coinflip
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: always
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge