version: '3'
services:
 mysql:
  image: mysql
  environment:
      - MYSQL_ROOT_PASSWORD=password
  ports:
     - '3306:3306'
 app:
  build: .
  environment:
     WAIT_HOSTS: mysql:3306
  ports:
     - '8080:8080'


